import './globals.css';
import Navigation from '@/components/Navigation';

export const metadata = {
  title: 'My Second Next App',
  description: 'Generated by create next app',
  keywords: 'React, Next, Js, App',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='stylesheet' href='https://bootswatch.com/5/flatly/bootstrap.min.css' />
      </head>
      <body>
        <Navigation />
        <div className='container p-4'>           
          {children}
        </div>
      </body>
    </html>
  );
};

/* Api utilizada para este projecto es reqres.in
 donde usaremos para este caso List user y single user
*/